name: C/C++ CI

on:
  push:
    branches: '**'
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Output of workspace 
      run: echo "Working directory: $GITHUB_WORKSPACE"    
      
    - name: make
      run: |
            cd src
            make
