name: C/C++ CI

on:
  push:
    branches: '**'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: fetch code 
      uses: actions/checkout@v4

    - name: install packages
      uses: sudo apt-get update; sudo apt-get install gcov cppcheck
      
    - name: Output of workspace 
      run: echo "Working directory: $GITHUB_WORKSPACE"    
      
    - name: make 
      run: cd ./src; make

    - name: make check
      run: cd ./src ; STATIC=0 COV=1 make check

    - name: coverage
      run: cd ./src ; STATIC=0 COV=1 make coverage
